/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CurrentUser } from "./store/auth.store";
export { CurrentUser } from "./store/auth.store";
export namespace Components {
    interface AppAddressSection {
        /**
          * @default ''
         */
        "address1": string;
        /**
          * @default ''
         */
        "address2": string;
        /**
          * @default ''
         */
        "city": string;
        /**
          * @default ''
         */
        "postalCode": string;
        /**
          * @default ''
         */
        "state": string;
    }
    interface AppCampaignEdit {
        "campaignId": string;
    }
    interface AppCampaignNew {
    }
    interface AppCampaigns {
    }
    interface AppDashboard {
    }
    interface AppDonationEdit {
        "donationId": string;
        "returnTo"?: string;
    }
    interface AppDonationImport {
    }
    interface AppDonationNew {
        "preselectedDonorId"?: string;
    }
    interface AppDonations {
    }
    interface AppDonorEdit {
        "donorId": string;
    }
    interface AppDonorHistory {
        "donorId": string;
    }
    interface AppDonorImport {
    }
    interface AppDonorNew {
    }
    interface AppDonors {
    }
    interface AppHeader {
        /**
          * @default null
         */
        "currentUser": CurrentUser | null;
        /**
          * @default null
         */
        "orgName": string | null;
    }
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppNav {
        /**
          * @default '/'
         */
        "currentPath": string;
    }
    interface AppPager {
        "page": number;
        "totalPages": number;
        "totalResults": number;
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface AppToast {
        "show": (message: string, variant?: ToastVariant) => Promise<void>;
    }
    interface AppUserEdit {
        "userId": string;
    }
    interface AppUserNew {
    }
    interface AppUsers {
    }
}
export interface AppAddressSectionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppAddressSectionElement;
}
export interface AppPagerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppPagerElement;
}
declare global {
    interface HTMLAppAddressSectionElementEventMap {
        "address1Change": string;
        "address2Change": string;
        "cityChange": string;
        "donorStateChange": string;
        "postalCodeChange": string;
    }
    interface HTMLAppAddressSectionElement extends Components.AppAddressSection, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppAddressSectionElementEventMap>(type: K, listener: (this: HTMLAppAddressSectionElement, ev: AppAddressSectionCustomEvent<HTMLAppAddressSectionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppAddressSectionElementEventMap>(type: K, listener: (this: HTMLAppAddressSectionElement, ev: AppAddressSectionCustomEvent<HTMLAppAddressSectionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppAddressSectionElement: {
        prototype: HTMLAppAddressSectionElement;
        new (): HTMLAppAddressSectionElement;
    };
    interface HTMLAppCampaignEditElement extends Components.AppCampaignEdit, HTMLStencilElement {
    }
    var HTMLAppCampaignEditElement: {
        prototype: HTMLAppCampaignEditElement;
        new (): HTMLAppCampaignEditElement;
    };
    interface HTMLAppCampaignNewElement extends Components.AppCampaignNew, HTMLStencilElement {
    }
    var HTMLAppCampaignNewElement: {
        prototype: HTMLAppCampaignNewElement;
        new (): HTMLAppCampaignNewElement;
    };
    interface HTMLAppCampaignsElement extends Components.AppCampaigns, HTMLStencilElement {
    }
    var HTMLAppCampaignsElement: {
        prototype: HTMLAppCampaignsElement;
        new (): HTMLAppCampaignsElement;
    };
    interface HTMLAppDashboardElement extends Components.AppDashboard, HTMLStencilElement {
    }
    var HTMLAppDashboardElement: {
        prototype: HTMLAppDashboardElement;
        new (): HTMLAppDashboardElement;
    };
    interface HTMLAppDonationEditElement extends Components.AppDonationEdit, HTMLStencilElement {
    }
    var HTMLAppDonationEditElement: {
        prototype: HTMLAppDonationEditElement;
        new (): HTMLAppDonationEditElement;
    };
    interface HTMLAppDonationImportElement extends Components.AppDonationImport, HTMLStencilElement {
    }
    var HTMLAppDonationImportElement: {
        prototype: HTMLAppDonationImportElement;
        new (): HTMLAppDonationImportElement;
    };
    interface HTMLAppDonationNewElement extends Components.AppDonationNew, HTMLStencilElement {
    }
    var HTMLAppDonationNewElement: {
        prototype: HTMLAppDonationNewElement;
        new (): HTMLAppDonationNewElement;
    };
    interface HTMLAppDonationsElement extends Components.AppDonations, HTMLStencilElement {
    }
    var HTMLAppDonationsElement: {
        prototype: HTMLAppDonationsElement;
        new (): HTMLAppDonationsElement;
    };
    interface HTMLAppDonorEditElement extends Components.AppDonorEdit, HTMLStencilElement {
    }
    var HTMLAppDonorEditElement: {
        prototype: HTMLAppDonorEditElement;
        new (): HTMLAppDonorEditElement;
    };
    interface HTMLAppDonorHistoryElement extends Components.AppDonorHistory, HTMLStencilElement {
    }
    var HTMLAppDonorHistoryElement: {
        prototype: HTMLAppDonorHistoryElement;
        new (): HTMLAppDonorHistoryElement;
    };
    interface HTMLAppDonorImportElement extends Components.AppDonorImport, HTMLStencilElement {
    }
    var HTMLAppDonorImportElement: {
        prototype: HTMLAppDonorImportElement;
        new (): HTMLAppDonorImportElement;
    };
    interface HTMLAppDonorNewElement extends Components.AppDonorNew, HTMLStencilElement {
    }
    var HTMLAppDonorNewElement: {
        prototype: HTMLAppDonorNewElement;
        new (): HTMLAppDonorNewElement;
    };
    interface HTMLAppDonorsElement extends Components.AppDonors, HTMLStencilElement {
    }
    var HTMLAppDonorsElement: {
        prototype: HTMLAppDonorsElement;
        new (): HTMLAppDonorsElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppPagerElementEventMap {
        "pageChange": number;
    }
    interface HTMLAppPagerElement extends Components.AppPager, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppPagerElementEventMap>(type: K, listener: (this: HTMLAppPagerElement, ev: AppPagerCustomEvent<HTMLAppPagerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppPagerElementEventMap>(type: K, listener: (this: HTMLAppPagerElement, ev: AppPagerCustomEvent<HTMLAppPagerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppPagerElement: {
        prototype: HTMLAppPagerElement;
        new (): HTMLAppPagerElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSettingsElement extends Components.AppSettings, HTMLStencilElement {
    }
    var HTMLAppSettingsElement: {
        prototype: HTMLAppSettingsElement;
        new (): HTMLAppSettingsElement;
    };
    interface HTMLAppToastElement extends Components.AppToast, HTMLStencilElement {
    }
    var HTMLAppToastElement: {
        prototype: HTMLAppToastElement;
        new (): HTMLAppToastElement;
    };
    interface HTMLAppUserEditElement extends Components.AppUserEdit, HTMLStencilElement {
    }
    var HTMLAppUserEditElement: {
        prototype: HTMLAppUserEditElement;
        new (): HTMLAppUserEditElement;
    };
    interface HTMLAppUserNewElement extends Components.AppUserNew, HTMLStencilElement {
    }
    var HTMLAppUserNewElement: {
        prototype: HTMLAppUserNewElement;
        new (): HTMLAppUserNewElement;
    };
    interface HTMLAppUsersElement extends Components.AppUsers, HTMLStencilElement {
    }
    var HTMLAppUsersElement: {
        prototype: HTMLAppUsersElement;
        new (): HTMLAppUsersElement;
    };
    interface HTMLElementTagNameMap {
        "app-address-section": HTMLAppAddressSectionElement;
        "app-campaign-edit": HTMLAppCampaignEditElement;
        "app-campaign-new": HTMLAppCampaignNewElement;
        "app-campaigns": HTMLAppCampaignsElement;
        "app-dashboard": HTMLAppDashboardElement;
        "app-donation-edit": HTMLAppDonationEditElement;
        "app-donation-import": HTMLAppDonationImportElement;
        "app-donation-new": HTMLAppDonationNewElement;
        "app-donations": HTMLAppDonationsElement;
        "app-donor-edit": HTMLAppDonorEditElement;
        "app-donor-history": HTMLAppDonorHistoryElement;
        "app-donor-import": HTMLAppDonorImportElement;
        "app-donor-new": HTMLAppDonorNewElement;
        "app-donors": HTMLAppDonorsElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-nav": HTMLAppNavElement;
        "app-pager": HTMLAppPagerElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-settings": HTMLAppSettingsElement;
        "app-toast": HTMLAppToastElement;
        "app-user-edit": HTMLAppUserEditElement;
        "app-user-new": HTMLAppUserNewElement;
        "app-users": HTMLAppUsersElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface AppAddressSection {
        /**
          * @default ''
         */
        "address1"?: string;
        /**
          * @default ''
         */
        "address2"?: string;
        /**
          * @default ''
         */
        "city"?: string;
        "onAddress1Change"?: (event: AppAddressSectionCustomEvent<string>) => void;
        "onAddress2Change"?: (event: AppAddressSectionCustomEvent<string>) => void;
        "onCityChange"?: (event: AppAddressSectionCustomEvent<string>) => void;
        "onDonorStateChange"?: (event: AppAddressSectionCustomEvent<string>) => void;
        "onPostalCodeChange"?: (event: AppAddressSectionCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "postalCode"?: string;
        /**
          * @default ''
         */
        "state"?: string;
    }
    interface AppCampaignEdit {
        "campaignId": string;
    }
    interface AppCampaignNew {
    }
    interface AppCampaigns {
    }
    interface AppDashboard {
    }
    interface AppDonationEdit {
        "donationId": string;
        "returnTo"?: string;
    }
    interface AppDonationImport {
    }
    interface AppDonationNew {
        "preselectedDonorId"?: string;
    }
    interface AppDonations {
    }
    interface AppDonorEdit {
        "donorId": string;
    }
    interface AppDonorHistory {
        "donorId": string;
    }
    interface AppDonorImport {
    }
    interface AppDonorNew {
    }
    interface AppDonors {
    }
    interface AppHeader {
        /**
          * @default null
         */
        "currentUser"?: CurrentUser | null;
        /**
          * @default null
         */
        "orgName"?: string | null;
    }
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppNav {
        /**
          * @default '/'
         */
        "currentPath"?: string;
    }
    interface AppPager {
        "onPageChange"?: (event: AppPagerCustomEvent<number>) => void;
        "page": number;
        "totalPages": number;
        "totalResults": number;
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface AppToast {
    }
    interface AppUserEdit {
        "userId": string;
    }
    interface AppUserNew {
    }
    interface AppUsers {
    }

    interface AppAddressSectionAttributes {
        "address1": string;
        "address2": string;
        "city": string;
        "state": string;
        "postalCode": string;
    }
    interface AppCampaignEditAttributes {
        "campaignId": string;
    }
    interface AppDonationEditAttributes {
        "donationId": string;
        "returnTo": string;
    }
    interface AppDonationNewAttributes {
        "preselectedDonorId": string;
    }
    interface AppDonorEditAttributes {
        "donorId": string;
    }
    interface AppDonorHistoryAttributes {
        "donorId": string;
    }
    interface AppHeaderAttributes {
        "orgName": string | null;
    }
    interface AppNavAttributes {
        "currentPath": string;
    }
    interface AppPagerAttributes {
        "page": number;
        "totalPages": number;
        "totalResults": number;
    }
    interface AppUserEditAttributes {
        "userId": string;
    }

    interface IntrinsicElements {
        "app-address-section": Omit<AppAddressSection, keyof AppAddressSectionAttributes> & { [K in keyof AppAddressSection & keyof AppAddressSectionAttributes]?: AppAddressSection[K] } & { [K in keyof AppAddressSection & keyof AppAddressSectionAttributes as `attr:${K}`]?: AppAddressSectionAttributes[K] } & { [K in keyof AppAddressSection & keyof AppAddressSectionAttributes as `prop:${K}`]?: AppAddressSection[K] };
        "app-campaign-edit": Omit<AppCampaignEdit, keyof AppCampaignEditAttributes> & { [K in keyof AppCampaignEdit & keyof AppCampaignEditAttributes]?: AppCampaignEdit[K] } & { [K in keyof AppCampaignEdit & keyof AppCampaignEditAttributes as `attr:${K}`]?: AppCampaignEditAttributes[K] } & { [K in keyof AppCampaignEdit & keyof AppCampaignEditAttributes as `prop:${K}`]?: AppCampaignEdit[K] } & OneOf<"campaignId", AppCampaignEdit["campaignId"], AppCampaignEditAttributes["campaignId"]>;
        "app-campaign-new": AppCampaignNew;
        "app-campaigns": AppCampaigns;
        "app-dashboard": AppDashboard;
        "app-donation-edit": Omit<AppDonationEdit, keyof AppDonationEditAttributes> & { [K in keyof AppDonationEdit & keyof AppDonationEditAttributes]?: AppDonationEdit[K] } & { [K in keyof AppDonationEdit & keyof AppDonationEditAttributes as `attr:${K}`]?: AppDonationEditAttributes[K] } & { [K in keyof AppDonationEdit & keyof AppDonationEditAttributes as `prop:${K}`]?: AppDonationEdit[K] } & OneOf<"donationId", AppDonationEdit["donationId"], AppDonationEditAttributes["donationId"]>;
        "app-donation-import": AppDonationImport;
        "app-donation-new": Omit<AppDonationNew, keyof AppDonationNewAttributes> & { [K in keyof AppDonationNew & keyof AppDonationNewAttributes]?: AppDonationNew[K] } & { [K in keyof AppDonationNew & keyof AppDonationNewAttributes as `attr:${K}`]?: AppDonationNewAttributes[K] } & { [K in keyof AppDonationNew & keyof AppDonationNewAttributes as `prop:${K}`]?: AppDonationNew[K] };
        "app-donations": AppDonations;
        "app-donor-edit": Omit<AppDonorEdit, keyof AppDonorEditAttributes> & { [K in keyof AppDonorEdit & keyof AppDonorEditAttributes]?: AppDonorEdit[K] } & { [K in keyof AppDonorEdit & keyof AppDonorEditAttributes as `attr:${K}`]?: AppDonorEditAttributes[K] } & { [K in keyof AppDonorEdit & keyof AppDonorEditAttributes as `prop:${K}`]?: AppDonorEdit[K] } & OneOf<"donorId", AppDonorEdit["donorId"], AppDonorEditAttributes["donorId"]>;
        "app-donor-history": Omit<AppDonorHistory, keyof AppDonorHistoryAttributes> & { [K in keyof AppDonorHistory & keyof AppDonorHistoryAttributes]?: AppDonorHistory[K] } & { [K in keyof AppDonorHistory & keyof AppDonorHistoryAttributes as `attr:${K}`]?: AppDonorHistoryAttributes[K] } & { [K in keyof AppDonorHistory & keyof AppDonorHistoryAttributes as `prop:${K}`]?: AppDonorHistory[K] } & OneOf<"donorId", AppDonorHistory["donorId"], AppDonorHistoryAttributes["donorId"]>;
        "app-donor-import": AppDonorImport;
        "app-donor-new": AppDonorNew;
        "app-donors": AppDonors;
        "app-header": Omit<AppHeader, keyof AppHeaderAttributes> & { [K in keyof AppHeader & keyof AppHeaderAttributes]?: AppHeader[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `attr:${K}`]?: AppHeaderAttributes[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `prop:${K}`]?: AppHeader[K] };
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-nav": Omit<AppNav, keyof AppNavAttributes> & { [K in keyof AppNav & keyof AppNavAttributes]?: AppNav[K] } & { [K in keyof AppNav & keyof AppNavAttributes as `attr:${K}`]?: AppNavAttributes[K] } & { [K in keyof AppNav & keyof AppNavAttributes as `prop:${K}`]?: AppNav[K] };
        "app-pager": Omit<AppPager, keyof AppPagerAttributes> & { [K in keyof AppPager & keyof AppPagerAttributes]?: AppPager[K] } & { [K in keyof AppPager & keyof AppPagerAttributes as `attr:${K}`]?: AppPagerAttributes[K] } & { [K in keyof AppPager & keyof AppPagerAttributes as `prop:${K}`]?: AppPager[K] } & OneOf<"page", AppPager["page"], AppPagerAttributes["page"]> & OneOf<"totalPages", AppPager["totalPages"], AppPagerAttributes["totalPages"]> & OneOf<"totalResults", AppPager["totalResults"], AppPagerAttributes["totalResults"]>;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-settings": AppSettings;
        "app-toast": AppToast;
        "app-user-edit": Omit<AppUserEdit, keyof AppUserEditAttributes> & { [K in keyof AppUserEdit & keyof AppUserEditAttributes]?: AppUserEdit[K] } & { [K in keyof AppUserEdit & keyof AppUserEditAttributes as `attr:${K}`]?: AppUserEditAttributes[K] } & { [K in keyof AppUserEdit & keyof AppUserEditAttributes as `prop:${K}`]?: AppUserEdit[K] } & OneOf<"userId", AppUserEdit["userId"], AppUserEditAttributes["userId"]>;
        "app-user-new": AppUserNew;
        "app-users": AppUsers;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-address-section": LocalJSX.IntrinsicElements["app-address-section"] & JSXBase.HTMLAttributes<HTMLAppAddressSectionElement>;
            "app-campaign-edit": LocalJSX.IntrinsicElements["app-campaign-edit"] & JSXBase.HTMLAttributes<HTMLAppCampaignEditElement>;
            "app-campaign-new": LocalJSX.IntrinsicElements["app-campaign-new"] & JSXBase.HTMLAttributes<HTMLAppCampaignNewElement>;
            "app-campaigns": LocalJSX.IntrinsicElements["app-campaigns"] & JSXBase.HTMLAttributes<HTMLAppCampaignsElement>;
            "app-dashboard": LocalJSX.IntrinsicElements["app-dashboard"] & JSXBase.HTMLAttributes<HTMLAppDashboardElement>;
            "app-donation-edit": LocalJSX.IntrinsicElements["app-donation-edit"] & JSXBase.HTMLAttributes<HTMLAppDonationEditElement>;
            "app-donation-import": LocalJSX.IntrinsicElements["app-donation-import"] & JSXBase.HTMLAttributes<HTMLAppDonationImportElement>;
            "app-donation-new": LocalJSX.IntrinsicElements["app-donation-new"] & JSXBase.HTMLAttributes<HTMLAppDonationNewElement>;
            "app-donations": LocalJSX.IntrinsicElements["app-donations"] & JSXBase.HTMLAttributes<HTMLAppDonationsElement>;
            "app-donor-edit": LocalJSX.IntrinsicElements["app-donor-edit"] & JSXBase.HTMLAttributes<HTMLAppDonorEditElement>;
            "app-donor-history": LocalJSX.IntrinsicElements["app-donor-history"] & JSXBase.HTMLAttributes<HTMLAppDonorHistoryElement>;
            "app-donor-import": LocalJSX.IntrinsicElements["app-donor-import"] & JSXBase.HTMLAttributes<HTMLAppDonorImportElement>;
            "app-donor-new": LocalJSX.IntrinsicElements["app-donor-new"] & JSXBase.HTMLAttributes<HTMLAppDonorNewElement>;
            "app-donors": LocalJSX.IntrinsicElements["app-donors"] & JSXBase.HTMLAttributes<HTMLAppDonorsElement>;
            "app-header": LocalJSX.IntrinsicElements["app-header"] & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.IntrinsicElements["app-home"] & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.IntrinsicElements["app-login"] & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-nav": LocalJSX.IntrinsicElements["app-nav"] & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-pager": LocalJSX.IntrinsicElements["app-pager"] & JSXBase.HTMLAttributes<HTMLAppPagerElement>;
            "app-profile": LocalJSX.IntrinsicElements["app-profile"] & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-settings": LocalJSX.IntrinsicElements["app-settings"] & JSXBase.HTMLAttributes<HTMLAppSettingsElement>;
            "app-toast": LocalJSX.IntrinsicElements["app-toast"] & JSXBase.HTMLAttributes<HTMLAppToastElement>;
            "app-user-edit": LocalJSX.IntrinsicElements["app-user-edit"] & JSXBase.HTMLAttributes<HTMLAppUserEditElement>;
            "app-user-new": LocalJSX.IntrinsicElements["app-user-new"] & JSXBase.HTMLAttributes<HTMLAppUserNewElement>;
            "app-users": LocalJSX.IntrinsicElements["app-users"] & JSXBase.HTMLAttributes<HTMLAppUsersElement>;
        }
    }
}
